services:
  apache:
    # image: 'php:7.2-apache'
    image: 'php:8-apache'
    networks:
      - my-network
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./www/:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb   

  mysqldb:
    container_name: mysql
    image: mysql:8.0
    networks:
      - my-network
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql      
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: estacio
      MYSQL_USER: estacio
      MYSQL_PASSWORD: senha

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - my-network
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mysqldb      

networks:
  my-network:      